name: Build and Release EXE

on:
  push:
    tags:
      - 'v*' # Trigger on tags that start with 'v', e.g., v1.0.0
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.x' # Adjust to your project’s target version

    - name: Restore dependencies
      run: dotnet restore GUI/Stepper_controller.csproj

    - name: Build solution
      run: dotnet build GUI/Stepper_controller.csproj --configuration Release --no-restore

    - name: Publish EXE
      run: dotnet publish GUI/Stepper_controller.csproj -c Release -r win-x64 --self-contained --output ./publish

    - name: Create ZIP of output
      run: |
        cd publish
        Compress-Archive -Path * -DestinationPath ../stepper-controller.zip

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: stepper-controller
        path: stepper-controller.zip

  release:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'push' || github.event.inputs.tag_name
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: stepper-controller

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: stepper-controller.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event_name == 'push' && github.ref || github.event.inputs.tag_name }}
        name: Release ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.tag_name }}
        draft: false
        prerelease: false
        body: |
          Automatically generated release.
