name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags that start with 'v', e.g., v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Adjust this based on your project’s target version

    - name: Restore dependencies
      run: dotnet restore GUI/Stepper_controller.csproj

    - name: Build the solution
      run: dotnet build GUI/Stepper_controller.csproj --configuration Release --no-restore

    - name: Publish the project
      run: dotnet publish GUI/Stepper_controller.csproj -c Release -r win-x64 --self-contained --output ./publish

    - name: Upload artifact for release
      uses: actions/upload-artifact@v3
      with:
        name: exe-output
        path: ./publish/

  release:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: exe-output

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: exe-output/**/*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          Automatically generated release.
